import math

import torch
from muon import adam_update


MUON_NS_COEFFS = (3.4445, -4.7750, 2.0315)
# Degree-five minimax schedule generated by the Polar Express reference code
# for l=1e-3, cushion=0.02, and a 1.01 BF16 safety factor.
POLAR_EXPRESS_COEFFS = (
    (8.237312490495555, -23.157747414558187, 16.6805684114459),
    (4.082441999064829, -2.8930477353325847, 0.5252849256975645),
    (3.9263479922546467, -2.8547468034765227, 0.5318022422894976),
    (3.298218713308518, -2.4245419810267106, 0.48632008358844153),
    (2.2970369434552604, -1.636625581259034, 0.40026284559536346),
    (1.8763805351440364, -1.234789657772217, 0.358918875016681),
    (1.8564423485523178, -1.213244988074968, 0.3568003487734798),
    (1.856435360469738, -1.2132371298535554, 0.35679936078169056),
    (1.8564311660205055, -1.2132289062936323, 0.35679533004165437),
    (1.8749954775650743, -1.2499909551519643, 0.3749954775868902),
)
ROW_NS_MAX_SINGULAR = 1.25


def _prepare_muon_matrix(G: torch.Tensor, eps: float = 1e-7):
    assert G.ndim >= 2
    X = G.to(dtype=torch.bfloat16)
    transposed = G.size(-2) > G.size(-1)
    if transposed:
        X = X.mT
    X = X / (X.norm(dim=(-2, -1), keepdim=True) + eps)
    return X, transposed


def _restore_muon_matrix(X: torch.Tensor, transposed: bool):
    return X.mT if transposed else X

@torch.compile
def _muon_ns5_prepared(X: torch.Tensor, steps: int):
    a, b, c = MUON_NS_COEFFS
    out = X
    for _ in range(steps):
        gram = out @ out.mT
        gram2 = gram @ gram
        out = a * out + (b * gram + c * gram2) @ out
    return out


@torch.compile
def _polar_express_prepared(X: torch.Tensor, steps: int):
    # The coefficient construction assumes an upper singular bound of one.
    # The extra 1.01 matches its finite-precision safety normalization.
    out = X / 1.01
    final_index = len(POLAR_EXPRESS_COEFFS) - 1
    for step in range(steps):
        a, b, c = POLAR_EXPRESS_COEFFS[min(step, final_index)]
        gram = out @ out.mT
        out = a * out + (b * gram + c * (gram @ gram)) @ out
    return out


def _polar_solve_prepared(X: torch.Tensor, steps: int, method: str):
    if method == "muon":
        return _muon_ns5_prepared(X, steps)
    if method == "polar_express":
        return _polar_express_prepared(X, steps)
    raise ValueError(f"Unknown polar method: {method!r}")

def _row_ns_higham_cubic(X, num_iters: int):
    Z = X
    for _ in range(num_iters):
        gram = Z @ Z.mT
        identity = torch.eye(
            gram.shape[-1], device=gram.device, dtype=gram.dtype
        )
        error = gram - identity
        # Algebraically identical to (15 I - 10 G + 3 G^2) X / 8,
        # but avoids cancellation between large BF16 terms near G = I.
        correction = -0.5 * error + 0.375 * (error @ error)
        Z = Z + correction @ Z
    return Z


def _row_ns_higham_cubic_w_cap(X, num_iters: int):
    Z = X

    gram = Z @ Z.mT

    upper_sq = gram.abs().sum(dim=-1).amax(dim=-1, keepdim=True).unsqueeze(-1)
    scale = (ROW_NS_MAX_SINGULAR / (upper_sq.sqrt() + 1e-7)).clamp(max=1.0)
    Z = Z * scale
    gram = gram * scale.square()

    identity = torch.eye(
        gram.shape[-1], device=gram.device, dtype=gram.dtype
    )
    error = gram - identity
    correction = -0.5 * error + 0.375 * (error @ error)
    Z = Z + correction @ Z

    for _ in range(num_iters - 1):
        gram = Z @ Z.mT
        error = gram - identity
        correction = -0.5 * error + 0.375 * (error @ error)
        Z = Z + correction @ Z
    return Z

def lower_bound_1(G: torch.Tensor):
    diag = torch.diagonal(G, dim1=-2, dim2=-1)
    off_abs_sum = G.abs().sum(dim=-1) - diag.abs()
    lower_sq = (diag - off_abs_sum).amin(dim=-1)
    lower = lower_sq.clamp_min(0).sqrt()
    return lower

def _row_ns_quadratic_w_cap(X, num_iters: int):
    Z = X

    gram = Z @ Z.mT

    upper_sq = gram.abs().sum(dim=-1).amax(dim=-1, keepdim=True).unsqueeze(-1)
    scale = (ROW_NS_MAX_SINGULAR / (upper_sq.sqrt() + 1e-7)).clamp(max=1.0)
    Z = Z * scale
    gram = gram * scale.square()

    identity = torch.eye(
        gram.shape[-1], device=gram.device, dtype=gram.dtype
    )
    error = gram - identity
    Z = Z - 0.5 * (error @ Z)

    for _ in range(num_iters - 1):
        gram = Z @ Z.mT
        error = gram - identity
        Z = Z - 0.5 * (error @ Z)
    return Z

def _row_ns_quadratic(X, num_iters: int):
    Z = X
    for _ in range(num_iters):
        gram = Z @ Z.mT
        identity = torch.eye(
            gram.shape[-1], device=gram.device, dtype=gram.dtype
        )
        error = gram - identity
        Z = Z - 0.5 * (error @ Z)
    return Z


def _row_ns_retract(
    X,
    num_iters: int,
    ns_method: str,
    cap_spectral_norm: bool = True,
):
    if ns_method == "higham_cubic":
        function = (
            _row_ns_higham_cubic_w_cap
            if cap_spectral_norm
            else _row_ns_higham_cubic
        )
        return function(X, num_iters)
    if ns_method == "quadratic":
        function = (
            _row_ns_quadratic_w_cap
            if cap_spectral_norm
            else _row_ns_quadratic
        )
        return function(X, num_iters)
    raise ValueError(f"Unknown muon_warm_retract_method: {ns_method!r}")

# @torch.compile
def _jacobi_scale(
    R: torch.Tensor,
    jacobi_eps: float,
    damping: str = "floor",
):
    diag = torch.diagonal(R)
    denom = diag.unsqueeze(1) + diag.unsqueeze(0)
    floor = jacobi_eps * (diag.abs().mean() + 1e-8)
    if damping == "tikhonov":
        return denom / (denom.square() + floor.square()).clamp_min(1e-30)
    if damping != "floor":
        raise ValueError(f"Unknown Jacobi damping: {damping!r}")
    denom_abs = denom.abs().clamp_min(floor)
    denom = torch.copysign(denom_abs, denom)
    return denom.reciprocal()


@torch.compile
def _warm_alignment_metrics(work_matrix, q_prev):
    """Return alignment matrix plus cheap rotation/subspace error proxies."""
    R = q_prev @ work_matrix.mT
    skew = 0.5 * (R - R.mT)
    matrix_norm = work_matrix.float().norm().clamp_min(1e-8)
    rotation_error = skew.float().norm() / R.float().norm().clamp_min(1e-8)
    # For row-orthonormal Q,
    # ||M (I - Q.T Q)||_F^2 = ||M||_F^2 - ||M Q.T||_F^2.
    subspace_sq = (
        matrix_norm.square() - R.float().square().sum()
    ).clamp_min(0.0)
    subspace_error = subspace_sq.sqrt() / matrix_norm
    diagonal = torch.diagonal(R).float()
    relative_min_alignment = diagonal.amin() / diagonal.abs().mean().clamp_min(1e-8)
    return R, torch.stack(
        (rotation_error, subspace_error, relative_min_alignment)
    )


def _warm_polar_jacobi_core(
    work_matrix,
    q_prev,
    eta: float,
    jacobi_eps: float,
    retract_method: str,
    retract_steps: int,
    track_subspace: bool = True,
    alignment_matrix=None,
    jacobi_damping: str = "floor",
    max_tangent_rms: float = 0.0,
    alignment_tolerance: float = -1.0,
    measure_tangent: bool = False,
    dynamic_tangent_cap=None,
):
    # Muon prepares matrices with rows <= columns, so Q has near-orthonormal rows.
    # Polar alignment asks for Q @ M.T to be symmetric.
    R = q_prev @ work_matrix.mT if alignment_matrix is None else alignment_matrix
    skew = 0.5 * (R - R.mT)
    # The skew term supplies the in-row-space tangent component.
    A = -2.0 * skew * _jacobi_scale(R, jacobi_eps, jacobi_damping)
    if track_subspace and work_matrix.shape[-1] > work_matrix.shape[-2]:
        # A @ Q only rotates rows inside Q's current row space.  Rectangular
        # polar factors also have a tangent component normal to that row space.
        # With D = diag(Q M.T), a diagonal approximation to the polar stretch,
        #
        #   D^-1 M + (A - D^-1 R.T) Q
        #
        # combines both tangent components while retaining the same two large
        # matmuls as the rotation-only update (R above and the product below).
        diag = torch.diagonal(R)
        floor = jacobi_eps * (diag.abs().mean() + 1e-8)
        if jacobi_damping == "tikhonov":
            inv_diag = diag / (
                diag.square() + floor.square()
            ).clamp_min(1e-30)
        else:
            diag_abs = diag.abs().clamp_min(floor)
            inv_diag = torch.copysign(diag_abs, diag).reciprocal()
        correction = inv_diag.unsqueeze(1) * work_matrix
        correction = correction + (
            A - inv_diag.unsqueeze(1) * R.mT
        ) @ q_prev
    else:
        correction = A @ q_prev

    effective_eta = work_matrix.new_tensor(float(eta), dtype=torch.float32)
    tangent_rms = effective_eta.new_tensor(-1.0)
    if (
        measure_tangent
        or max_tangent_rms > 0.0
        or dynamic_tangent_cap is not None
    ):
        tangent_rms = correction.float().norm() / math.sqrt(
            max(1, correction.shape[-2])
        )
    tangent_cap = dynamic_tangent_cap
    if max_tangent_rms > 0.0:
        fixed_cap = effective_eta.new_tensor(float(max_tangent_rms))
        tangent_cap = (
            fixed_cap
            if tangent_cap is None
            else torch.minimum(fixed_cap, tangent_cap)
        )
    if tangent_cap is not None:
        effective_eta = torch.minimum(
            effective_eta,
            tangent_cap / tangent_rms.clamp_min(1e-12),
        )
    q_tilde = q_prev + effective_eta.to(q_prev.dtype) * correction
    q_next = _row_ns_retract(q_tilde, retract_steps, retract_method)

    accepted = effective_eta.new_tensor(1.0)
    if alignment_tolerance >= 0.0:
        old_alignment = (q_prev.float() * work_matrix.float()).sum()
        new_alignment = (q_next.float() * work_matrix.float()).sum()
        accept = new_alignment + (
            float(alignment_tolerance) * old_alignment.abs()
        ) >= old_alignment
        q_next = torch.where(accept, q_next, q_prev)
        accepted = accept.to(torch.float32)
    stats = torch.stack((effective_eta, tangent_rms, accepted))
    return q_next, stats


@torch.compile
def _warm_polar_jacobi_step(
    work_matrix,
    q_prev,
    eta: float,
    jacobi_eps: float,
    retract_method: str,
    retract_steps: int,
    track_subspace: bool = True,
    alignment_matrix=None,
    jacobi_damping: str = "floor",
    max_tangent_rms: float = 0.0,
    alignment_tolerance: float = -1.0,
):
    return _warm_polar_jacobi_core(
        work_matrix,
        q_prev,
        eta,
        jacobi_eps,
        retract_method,
        retract_steps,
        track_subspace,
        alignment_matrix,
        jacobi_damping,
        max_tangent_rms,
        alignment_tolerance,
        False,
        None,
    )[0]


@torch.compile
def _warm_polar_jacobi_step_with_stats(
    work_matrix,
    q_prev,
    eta: float,
    jacobi_eps: float,
    retract_method: str,
    retract_steps: int,
    track_subspace: bool,
    alignment_matrix,
    jacobi_damping: str,
    max_tangent_rms: float,
    alignment_tolerance: float,
    dynamic_tangent_cap=None,
):
    return _warm_polar_jacobi_core(
        work_matrix,
        q_prev,
        eta,
        jacobi_eps,
        retract_method,
        retract_steps,
        track_subspace,
        alignment_matrix,
        jacobi_damping,
        max_tangent_rms,
        alignment_tolerance,
        True,
        dynamic_tangent_cap,
    )


class MuonWarm(torch.optim.Optimizer):
    """
    Muon optimizer with auxiliary Adam for non-matrix params.
    
    Supports double momentum mode (inspired by AdEMAMix) for muon params:
    - muon_double_momentum_mode=None: Standard single momentum
    - muon_double_momentum_mode="pre_ns": Blend fast/slow momentum before Newton-Schulz
    - muon_double_momentum_mode="post_ns": Apply NS to both, blend after
    
    Args:
        params: Model parameters or param_groups (use get_muon_param_groups helper)
        adam_lr: Learning rate for Adam params (default: 3e-4)
        adam_betas: Beta coefficients for Adam (default: (0.9, 0.95))
        adam_eps: Epsilon for Adam (default: 1e-10)
        adam_weight_decay: Weight decay for Adam params (default: 0)
        muon_lr: Learning rate for Muon params (default: 0.02)
        muon_momentum: Fast momentum beta for Muon (default: 0.95)
        muon_weight_decay: Weight decay for Muon params (default: 0)
        muon_ns_steps: Newton-Schulz iteration steps (default: 5)
        muon_nesterov: Use Nesterov momentum (default: True)
    """
    def __init__(
        self,
        params,
        # Adam params
        adam_lr=3e-4,
        adam_betas=(0.9, 0.999),
        adam_eps=1e-10,
        adam_weight_decay=0,
        # Muon params
        muon_lr=0.02,
        muon_momentum=0.95,
        muon_weight_decay=0,
        muon_ns_steps=5,
        muon_polar_method="muon",
        muon_nesterov=True,
        muon_warm_anchor_every=8,
        muon_warm_lr=1.0,
        muon_warm_jacobi_eps=1e-3,
        muon_warm_retract_method="higham_cubic",
        muon_warm_retract_steps=1,
        muon_warm_anchor_retract_method="higham_cubic",
        muon_warm_anchor_retract_steps=2,
        muon_warm_full_ns_steps=2500,
        muon_warm_track_subspace=True,
        muon_warm_max_tracking_error=0.0,
        muon_warm_min_alignment=0.0,
        muon_warm_check_every=1,
        muon_warm_stagger_anchors=False,
        muon_warm_jacobi_damping="floor",
        muon_warm_max_tangent_rms=0.0,
        muon_warm_alignment_tolerance=-1.0,
        muon_warm_record_stats=False,
        muon_warm_tangent_ema_beta=0.95,
        muon_warm_max_tangent_ratio=0.0,
    ):
        # Store muon-specific settings
        self.muon_ns_steps = muon_ns_steps
        self.muon_polar_method = muon_polar_method
        self.muon_nesterov = muon_nesterov
        self.muon_warm_anchor_every = muon_warm_anchor_every
        self.muon_warm_lr = muon_warm_lr
        self.muon_warm_jacobi_eps = muon_warm_jacobi_eps
        self.muon_warm_retract_method = muon_warm_retract_method
        self.muon_warm_retract_steps = muon_warm_retract_steps
        self.muon_warm_anchor_retract_method = (
            muon_warm_anchor_retract_method
        )
        self.muon_warm_anchor_retract_steps = int(
            muon_warm_anchor_retract_steps
        )
        self.muon_warm_full_ns_steps = max(0, int(muon_warm_full_ns_steps))
        self.muon_warm_track_subspace = bool(muon_warm_track_subspace)
        self.muon_warm_max_tracking_error = float(muon_warm_max_tracking_error)
        self.muon_warm_min_alignment = float(muon_warm_min_alignment)
        self.muon_warm_check_every = max(1, int(muon_warm_check_every))
        self.muon_warm_stagger_anchors = bool(muon_warm_stagger_anchors)
        self.muon_warm_jacobi_damping = muon_warm_jacobi_damping
        self.muon_warm_max_tangent_rms = float(muon_warm_max_tangent_rms)
        self.muon_warm_alignment_tolerance = float(
            muon_warm_alignment_tolerance
        )
        self.muon_warm_record_stats = bool(muon_warm_record_stats)
        self.muon_warm_tangent_ema_beta = float(muon_warm_tangent_ema_beta)
        self.muon_warm_max_tangent_ratio = float(muon_warm_max_tangent_ratio)
        self._next_muon_anchor_offset = 0
        if self.muon_warm_lr < 0.0:
            raise ValueError("muon_warm_lr must be non-negative")
        if self.muon_warm_max_tracking_error < 0.0:
            raise ValueError("muon_warm_max_tracking_error must be non-negative")
        if self.muon_warm_min_alignment < 0.0:
            raise ValueError("muon_warm_min_alignment must be non-negative")
        if self.muon_warm_jacobi_damping not in ("floor", "tikhonov"):
            raise ValueError(
                "muon_warm_jacobi_damping must be 'floor' or 'tikhonov'"
            )
        if self.muon_polar_method not in ("muon", "polar_express"):
            raise ValueError(
                "muon_polar_method must be 'muon' or 'polar_express'"
            )
        if self.muon_warm_max_tangent_rms < 0.0:
            raise ValueError("muon_warm_max_tangent_rms must be non-negative")
        if not 0.0 <= self.muon_warm_tangent_ema_beta < 1.0:
            raise ValueError(
                "muon_warm_tangent_ema_beta must be in [0, 1)"
            )
        if self.muon_warm_max_tangent_ratio < 0.0:
            raise ValueError(
                "muon_warm_max_tangent_ratio must be non-negative"
            )
        if self.muon_warm_retract_method not in ("higham_cubic", "quadratic"):
            raise ValueError(
                "muon_warm_retract_method must be 'higham_cubic' or 'quadratic', "
                f"got {self.muon_warm_retract_method!r}"
            )
        if self.muon_warm_anchor_retract_method not in (
            "higham_cubic",
            "quadratic",
        ):
            raise ValueError(
                "muon_warm_anchor_retract_method must be 'higham_cubic' "
                f"or 'quadratic', got {self.muon_warm_anchor_retract_method!r}"
            )
        if self.muon_warm_anchor_retract_steps < 0:
            raise ValueError(
                "muon_warm_anchor_retract_steps must be non-negative"
            )
        
        # Convert params to param_groups if needed
        if isinstance(params, dict):
            param_groups = [params]
        elif hasattr(params, '__iter__') and not isinstance(params, torch.Tensor):
            param_groups = list(params)
            if len(param_groups) > 0 and not isinstance(param_groups[0], dict):
                # It's an iterable of tensors, not param groups
                param_groups = [{"params": param_groups}]
        else:
            param_groups = [{"params": [params]}]
        
        # Apply defaults to each group
        for group in param_groups:
            if "use_muon" not in group:
                # Default: use muon for 2D+, adam for 1D
                # This shouldn't happen if using get_muon_param_groups
                group["use_muon"] = True
            
            if group["use_muon"]:
                group.setdefault("lr", muon_lr)
                group.setdefault("momentum", muon_momentum)
                group.setdefault("weight_decay", muon_weight_decay)
            else:
                group.setdefault("lr", adam_lr)
                group.setdefault("betas", adam_betas)
                group.setdefault("eps", adam_eps)
                group.setdefault("weight_decay", adam_weight_decay)
        
        super().__init__(param_groups, dict())

    def _prepare_tracking_matrix(
        self,
        work_matrix,
        q_prev,
        state,
        transposed,
    ):
        """Return the matrix whose polar factor is tracked between anchors."""
        return work_matrix

    def _compute_anchor_direction(self, work_matrix, state, transposed):
        q_next = _polar_solve_prepared(
            work_matrix,
            self.muon_ns_steps,
            self.muon_polar_method,
        )
        return _row_ns_retract(
            q_next,
            self.muon_warm_anchor_retract_steps,
            self.muon_warm_anchor_retract_method,
            False,
        )

    def _compute_warm_direction(
        self,
        tracking_matrix,
        q_prev,
        alignment_matrix,
        state,
        transposed,
    ):
        arguments = (
            tracking_matrix,
            q_prev,
            float(self.muon_warm_lr),
            float(self.muon_warm_jacobi_eps),
            self.muon_warm_retract_method,
            max(1, int(self.muon_warm_retract_steps)),
            self.muon_warm_track_subspace,
            alignment_matrix,
            self.muon_warm_jacobi_damping,
        )
        if (
            self.muon_warm_max_tangent_rms <= 0.0
            and self.muon_warm_alignment_tolerance < 0.0
            and not self.muon_warm_record_stats
            and self.muon_warm_max_tangent_ratio <= 0.0
        ):
            return _warm_polar_jacobi_step(*arguments)
        tangent_ema_sq = state.get("muon_warm_tangent_ema_sq_tensor")
        dynamic_tangent_cap = None
        if (
            self.muon_warm_max_tangent_ratio > 0.0
            and tangent_ema_sq is not None
        ):
            dynamic_tangent_cap = (
                float(self.muon_warm_max_tangent_ratio)
                * tangent_ema_sq.sqrt()
            )
        q_next, stats = _warm_polar_jacobi_step_with_stats(
            *arguments,
            self.muon_warm_max_tangent_rms,
            self.muon_warm_alignment_tolerance,
            dynamic_tangent_cap,
        )
        state["muon_warm_effective_eta_tensor"] = stats[0]
        state["muon_warm_tangent_rms_tensor"] = stats[1]
        state["muon_warm_step_accepted_tensor"] = stats[2]
        if self.muon_warm_max_tangent_ratio > 0.0:
            proposed_square = stats[1].square()
            if tangent_ema_sq is None:
                tangent_ema_sq = proposed_square
            else:
                tangent_ema_sq = tangent_ema_sq.lerp(
                    proposed_square,
                    1.0 - self.muon_warm_tangent_ema_beta,
                )
            state["muon_warm_tangent_ema_sq_tensor"] = tangent_ema_sq
            state["muon_warm_dynamic_cap_tensor"] = (
                dynamic_tangent_cap
                if dynamic_tangent_cap is not None
                else stats[1].new_tensor(-1.0)
            )
        return q_next

    def _muon_update_warm(self, grad, state, group):
        state["momentum_fast"].lerp_(grad, 1 - group["momentum"])
        update = (
            torch.lerp(grad, state["momentum_fast"], group["momentum"])
            if self.muon_nesterov
            else state["momentum_fast"]
        )
        original_shape = update.shape
        if update.ndim == 4:
            update = update.view(len(update), -1)

        work_matrix, transposed = _prepare_muon_matrix(update)
        q_prev = state.get("muon_warm_q")
        anchor_offset = (
            state.get("muon_warm_anchor_offset", 0)
            if self.muon_warm_stagger_anchors
            else 0
        )
        needs_anchor = (
            q_prev is None
            or q_prev.shape != work_matrix.shape
            or q_prev.device != work_matrix.device
            or q_prev.dtype != work_matrix.dtype
            or state["step"] <= self.muon_warm_full_ns_steps
            or (
                self.muon_warm_anchor_every > 0
                and (state["step"] + anchor_offset)
                % self.muon_warm_anchor_every
                == 0
            )
        )
        tracking_matrix = (
            work_matrix
            if needs_anchor
            else self._prepare_tracking_matrix(
                work_matrix,
                q_prev,
                state,
                transposed,
            )
        )
        alignment_matrix = None
        check_tracking = (
            not needs_anchor
            and (
                self.muon_warm_max_tracking_error > 0.0
                or self.muon_warm_min_alignment > 0.0
            )
            and state["step"] % self.muon_warm_check_every == 0
        )
        if check_tracking:
            alignment_matrix, metrics = _warm_alignment_metrics(
                tracking_matrix, q_prev
            )
            rotation_error, subspace_error, relative_alignment = metrics.tolist()
            state["muon_warm_rotation_error"] = rotation_error
            state["muon_warm_subspace_error"] = subspace_error
            state["muon_warm_relative_alignment"] = relative_alignment
            needs_anchor = (
                (
                    self.muon_warm_max_tracking_error > 0.0
                    and max(rotation_error, subspace_error)
                    > self.muon_warm_max_tracking_error
                )
                or (
                    self.muon_warm_min_alignment > 0.0
                    and relative_alignment < self.muon_warm_min_alignment
                )
            )
        if needs_anchor:
            q_next = self._compute_anchor_direction(
                work_matrix,
                state,
                transposed,
            )
        else:
            q_next = self._compute_warm_direction(
                tracking_matrix,
                q_prev,
                alignment_matrix,
                state,
                transposed,
            )
        state["muon_warm_did_anchor"] = bool(needs_anchor)
        state["muon_warm_age"] = (
            0 if needs_anchor else int(state.get("muon_warm_age", 0)) + 1
        )
        state["muon_warm_q"] = q_next.contiguous()

        update = _restore_muon_matrix(q_next, transposed)
        # Keep aspect-ratio scaling out of place.  `_restore_muon_matrix` may
        # return the same storage as the cached q_next, depending on layout.
        update = update * max(1, update.size(-2) / update.size(-1)) ** 0.5
        return update.reshape(original_shape) if update.shape != original_shape else update

    @torch.no_grad()
    def step(self, closure=None):

        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        for group in self.param_groups:
            if group["use_muon"]:
                for p in group["params"]:
                    if p.grad is None:
                        p.grad = torch.zeros_like(p)  # Force synchronization
                    state = self.state[p]
                    
                    if len(state) == 0:
                        state["momentum_fast"] = torch.zeros_like(p)
                        state["step"] = 0
                        if self.muon_warm_anchor_every > 0:
                            state["muon_warm_anchor_offset"] = (
                                self._next_muon_anchor_offset
                                % self.muon_warm_anchor_every
                            )
                            self._next_muon_anchor_offset += 1
                    
                    state["step"] += 1
                    
                    update = self._muon_update_warm(p.grad, state, group)
                    
                    p.mul_(1 - group["lr"] * group["weight_decay"])
                    p.add_(update.reshape(p.shape), alpha=-group["lr"])
            else:
                for p in group["params"]:
                    if p.grad is None:
                        p.grad = torch.zeros_like(p)  # Force synchronization
                    state = self.state[p]
                    if len(state) == 0:
                        state["exp_avg"] = torch.zeros_like(p)
                        state["exp_avg_sq"] = torch.zeros_like(p)
                        state["step"] = 0
                    state["step"] += 1
                    update = adam_update(p.grad, state["exp_avg"], state["exp_avg_sq"],
                                         state["step"], group["betas"], group["eps"])
                    p.mul_(1 - group["lr"] * group["weight_decay"])
                    p.add_(update, alpha=-group["lr"])

        return loss
